# Generated by Django 2.1.3 on 2018-11-28 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('menu', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('businessCategory', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('microReview', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('options', models.CharField(max_length=100)),
                ('totalReviewCount', models.CharField(max_length=100)),
                ('roadAddr', models.CharField(max_length=100)),
                ('commonAddr', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('imageSrc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
