# Generated by Django 2.1.3 on 2018-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('businessCategory', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('microReview', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('options', models.CharField(max_length=100)),
                ('totalReviewCount', models.CharField(max_length=100)),
                ('roadAddr', models.CharField(max_length=100)),
                ('commonAddr', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('imageSrc', models.CharField(max_length=200)),
            ],
        ),
    ]
