# Generated by Django 2.1.3 on 2018-11-29 13:32

import data.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=data.models.post_image_path),
        ),
    ]
