# Generated by Django 2.1.3 on 2018-11-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181129_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='reivew',
        ),
    ]
