# Generated by Django 2.1.3 on 2018-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181129_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='totalReviewCount',
            field=models.IntegerField(),
        ),
    ]
