# Generated by Django 2.1.3 on 2018-12-03 14:59

import data.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20181202_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=data.models.post_image_path),
        ),
    ]
