# Generated by Django 2.1.3 on 2018-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
